#!/usr/bin/env bash
#installing nginx web server
sudo apt-get -y update
sudo apt-get install -y --allow-downgrades nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo "Hello World!" | sudo tee -a /var/www/html/index.html
