#!/usr/bin/env bash
#script to install and configure HAproxy
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen byakkogit \n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 3489-web-01 34.148.170.206:80 check\n\tserver 3489-web-02 34.148.139.135:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
